server:
  port: 40100
spring:
  application:
    name: u-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.233.140:3306/mo_yu_ucenter?characterEncoding=utf-8&useSSL=false&useUnicode=true
    username: root
    password: du522425
  redis:
    database: 2 #我的0号库使用在其他项目上，我用2号库
    host: 106.13.233.140
    port: 6379
    password: du522425
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出Sql语句执行日志
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/www/bugdr/ucenter/mapper/xml/*xml